server:
  port: 6969
spring:
  application:
    name: gateway_zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
zuul:
  routes:
    userService:
      path: /eureka-userService/**
    userConsumer:
      path: /eureka-userConsumer/**
  ratelimit:
    enabled: true
    policies:
      userConsumer:
        limit: 5